version: '3.8'

services:
  db:
    image: postgres:15
    container_name: telemetry_db
    environment:
      POSTGRES_USER: telemetry
      POSTGRES_PASSWORD: telemetrypass
      POSTGRES_DB: telemetry
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
