[env:esp32s3_gateway]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino

monitor_speed = 115200
upload_speed = 115200

lib_deps = 
  bblanchon/ArduinoJson@^7.0.0
  sparkfun/SparkFun MAX1704x Fuel Gauge Arduino Library@^1.0.4

lib_extra_dirs = 
  ../lib

build_flags = 
  -DBOARD_HAS_PSRAM=0