[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
lib_extra_dirs = ../lib
upload_port = /dev/cu.usbserial-5
monitor_port = /dev/cu.usbserial-5

lib_deps =
  bblanchon/ArduinoJson@^6.21.2