#!/usr/bin/env python3
"""Generate golden vectors for the wire formats in schema/PROTOCOL.md.

Outputs, all committed:
  schema/vectors/records.json        record codec, for TypeScript and Go tests
  schema/vectors/records_vectors.h   the same, for the firmware's Unity tests
  schema/vectors/ble.json            BLE payloads: advertising, device info,
                                     control commands, status, data chunks
  schema/vectors/ble_vectors.h       the same, for Unity

CI re-runs this script with --check and fails if the committed files differ.

Usage: python3 schema/tools/gen_vectors.py [--check]
"""
from __future__ import annotations

import json
import struct
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
VECTORS = HERE.parent / "vectors"

PROTOCOL_VERSION = 1

# ---------------------------------------------------------------------------
# Record (§1)
# ---------------------------------------------------------------------------

RECORD_VERSION = 1
RECORD_SIZE = 20
FLAG_EPOCH_VALID = 0x01

TYPE_SOIL_RESISTANCE_OHMS = 1
TYPE_BATTERY_MILLIVOLTS = 2

QUALITY_OK, QUALITY_LOW, QUALITY_HIGH, QUALITY_OPEN = 0, 1, 2, 3

EPOCH_2026_09_23 = 1790121600


def crc16_ccitt_false(data: bytes) -> int:
    crc = 0xFFFF
    for b in data:
        crc ^= b << 8
        for _ in range(8):
            if crc & 0x8000:
                crc = ((crc << 1) ^ 0x1021) & 0xFFFF
            else:
                crc = (crc << 1) & 0xFFFF
    return crc


def encode_record(r: dict) -> bytes:
    body = struct.pack(
        "<BBBBIIfH",
        r["version"], r["type"], r["quality"], r["flags"],
        r["seq"], r["time"], r["value"], r["boot_id"],
    )
    assert len(body) == RECORD_SIZE - 2
    return body + struct.pack("<H", crc16_ccitt_false(body))


def record(name: str, **fields) -> dict:
    r = {"version": RECORD_VERSION, **fields}
    return {"name": name, "hex": encode_record(r).hex(), "record": r}


VALID_RECORDS = [
    record(
        "soil_ok_epoch",
        type=TYPE_SOIL_RESISTANCE_OHMS, quality=QUALITY_OK, flags=FLAG_EPOCH_VALID,
        seq=1, time=EPOCH_2026_09_23, value=83520.0, boot_id=3,
    ),
    record(
        "soil_open_uptime",
        type=TYPE_SOIL_RESISTANCE_OHMS, quality=QUALITY_OPEN, flags=0,
        seq=4711, time=3600, value=-1.0, boot_id=1,
    ),
    record(
        "soil_low_first_seq",
        type=TYPE_SOIL_RESISTANCE_OHMS, quality=QUALITY_LOW, flags=0,
        seq=0, time=0, value=0.0, boot_id=0,
    ),
    record(
        "soil_high_large_value",
        type=TYPE_SOIL_RESISTANCE_OHMS, quality=QUALITY_HIGH, flags=FLAG_EPOCH_VALID,
        seq=1_000_000, time=EPOCH_2026_09_23 + 86_400, value=1_000_000.0, boot_id=12,
    ),
    record(
        "battery_max_counters",
        type=TYPE_BATTERY_MILLIVOLTS, quality=QUALITY_OK, flags=FLAG_EPOCH_VALID,
        seq=0xFFFFFFFF, time=0xFFFFFFFF, value=3712.0, boot_id=0xFFFF,
    ),
    record(
        "unknown_type_still_decodes",
        type=250, quality=QUALITY_OK, flags=0,
        seq=7, time=42, value=1.5, boot_id=2,
    ),
]


def invalid_records() -> list[dict]:
    base = bytes.fromhex(VALID_RECORDS[0]["hex"])

    bad_crc = bytearray(base)
    bad_crc[-1] ^= 0x01

    bad_version = bytearray(base)
    bad_version[0] = 2
    # CRC is recomputed so the version check, not the CRC check, must fire.
    bad_version[18:20] = struct.pack("<H", crc16_ccitt_false(bytes(bad_version[:18])))

    return [
        {"name": "short_input", "hex": base[:-1].hex(), "error": "short_input"},
        {"name": "unsupported_version", "hex": bytes(bad_version).hex(), "error": "unsupported_version"},
        {"name": "bad_crc", "hex": bytes(bad_crc).hex(), "error": "bad_crc"},
    ]


def build_records_json() -> str:
    doc = {
        "format": "record",
        "version": RECORD_VERSION,
        "size": RECORD_SIZE,
        "crc": {"name": "CRC-16/CCITT-FALSE", "check_input": "123456789", "check": "29b1"},
        "valid": VALID_RECORDS,
        "invalid": invalid_records(),
    }
    return json.dumps(doc, indent=2) + "\n"


def c_bytes(b: bytes) -> str:
    return ", ".join(f"0x{x:02x}" for x in b)


def c_float(v: float) -> str:
    s = repr(float(v))
    if "e" in s or "E" in s:
        s = f"{v:.1f}"
    return s + "f"


def build_records_header() -> str:
    lines = [
        "// Generated by schema/tools/gen_vectors.py. Do not edit.",
        "#pragma once",
        "#include <stddef.h>",
        "#include <stdint.h>",
        "",
        f"#define RECORD_VECTOR_VERSION {RECORD_VERSION}",
        f"#define RECORD_VECTOR_SIZE {RECORD_SIZE}",
        "",
        "struct RecordVector {",
        "    const char* name;",
        f"    uint8_t bytes[{RECORD_SIZE}];",
        "    uint8_t version, type, quality, flags;",
        "    uint32_t seq, time;",
        "    float value;",
        "    uint16_t boot_id;",
        "};",
        "",
        "static const RecordVector kRecordVectors[] = {",
    ]
    for v in VALID_RECORDS:
        r = v["record"]
        lines.append(
            f'    {{"{v["name"]}", {{{c_bytes(bytes.fromhex(v["hex"]))}}}, '
            f'{r["version"]}, {r["type"]}, {r["quality"]}, {r["flags"]}, '
            f'{r["seq"]}u, {r["time"]}u, {c_float(r["value"])}, {r["boot_id"]}}},'
        )
    lines += [
        "};",
        f"static const size_t kRecordVectorCount = {len(VALID_RECORDS)};",
        "",
        "struct InvalidRecordVector {",
        "    const char* name;",
        "    size_t len;",
        f"    uint8_t bytes[{RECORD_SIZE}];",
        "    const char* error;",
        "};",
        "",
        "static const InvalidRecordVector kInvalidRecordVectors[] = {",
    ]
    for v in invalid_records():
        b = bytes.fromhex(v["hex"])
        padded = b + bytes(RECORD_SIZE - len(b))
        lines.append(f'    {{"{v["name"]}", {len(b)}, {{{c_bytes(padded)}}}, "{v["error"]}"}},')
    lines += [
        "};",
        f"static const size_t kInvalidRecordVectorCount = {len(invalid_records())};",
        "",
    ]
    return "\n".join(lines)


# ---------------------------------------------------------------------------
# BLE sync service (§3)
# ---------------------------------------------------------------------------

SERVICE_UUID = "6eaedc54-f770-40e3-9806-a6ccf63c8099"
CHAR_DEVICE_INFO = "6eaedc54-f770-40e3-0001-a6ccf63c8099"
CHAR_CONTROL = "6eaedc54-f770-40e3-0002-a6ccf63c8099"
CHAR_DATA = "6eaedc54-f770-40e3-0003-a6ccf63c8099"
CHAR_STATUS = "6eaedc54-f770-40e3-0004-a6ccf63c8099"

ADVERTISING_SIZE = 6
DEVICE_INFO_SIZE = 54
STATUS_SIZE = 6
CHUNK_HEADER_SIZE = 8
MAX_RECORDS_PER_CHUNK = 24

ADV_FLAG_TIME_SET = 0x01
ADV_FLAG_DROPPED = 0x02
CHUNK_FLAG_LAST = 0x01

OPCODES = {
    "OPEN_SESSION": 0x01,
    "SET_TIME": 0x02,
    "READ_FROM": 0x03,
    "ACK_COLLECTED": 0x04,
    "ACK_SECURED": 0x05,
    "CLOSE_SESSION": 0x06,
}

RESULTS = {"ok": 0, "no_session": 1, "bad_argument": 2, "seq_out_of_range": 3, "busy": 4}

DEVICE_ID = bytes.fromhex("aabbccddeeff")
SESSION_ID = bytes.fromhex("7a1c2e3f12344bcd9ef00123456789ab")


def encode_advertising(a: dict) -> bytes:
    return struct.pack("<BHHB", a["protocol_version"], a["pending"], a["battery_mv"], a["adv_flags"])


def encode_device_info(d: dict) -> bytes:
    fw = d["fw_version"].encode("ascii")
    assert len(fw) <= 16
    out = struct.pack(
        "<BB6sHIIIIIIHH16s",
        d["protocol_version"], d["record_size"], bytes.fromhex(d["device_id"]),
        d["boot_id"], d["next_seq"], d["collected_through"], d["secured_through"],
        d["uptime_s"], d["unix_time"], d["dropped"], d["battery_mv"], d["capacity"],
        fw.ljust(16, b"\0"),
    )
    assert len(out) == DEVICE_INFO_SIZE
    return out


def encode_status(s: dict) -> bytes:
    return struct.pack("<BBI", s["opcode"], s["result"], s["seq"])


def encode_command(c: dict) -> bytes:
    op = OPCODES[c["name"]]
    if c["name"] == "OPEN_SESSION":
        return struct.pack("<B", op) + bytes.fromhex(c["session_id"])
    if c["name"] == "SET_TIME":
        return struct.pack("<BI", op, c["unix_time"])
    if c["name"] == "READ_FROM":
        return struct.pack("<BIH", op, c["seq"], c["max_records"])
    if c["name"] in ("ACK_COLLECTED", "ACK_SECURED"):
        return struct.pack("<BI", op, c["through_seq"])
    if c["name"] == "CLOSE_SESSION":
        return struct.pack("<B", op)
    raise ValueError(c["name"])


def encode_chunk(first_seq: int, flags: int, records: list[bytes]) -> bytes:
    body = b"".join(records)
    header = struct.pack("<IBBH", first_seq, len(records), flags, crc16_ccitt_false(body))
    return header + body


ADVERTISING = [
    {"name": "idle_no_time", "fields": {"protocol_version": 1, "pending": 0, "battery_mv": 0, "adv_flags": 0}},
    {"name": "pending_time_set", "fields": {"protocol_version": 1, "pending": 1440, "battery_mv": 3712, "adv_flags": ADV_FLAG_TIME_SET}},
    {"name": "saturated_with_drops", "fields": {"protocol_version": 1, "pending": 65535, "battery_mv": 3300, "adv_flags": ADV_FLAG_TIME_SET | ADV_FLAG_DROPPED}},
]
for a in ADVERTISING:
    a["hex"] = encode_advertising(a["fields"]).hex()

DEVICE_INFO = [
    {
        "name": "fresh_device",
        "fields": {
            "protocol_version": 1, "record_size": RECORD_SIZE, "device_id": DEVICE_ID.hex(),
            "boot_id": 1, "next_seq": 1, "collected_through": 0, "secured_through": 0,
            "uptime_s": 12, "unix_time": 0, "dropped": 0, "battery_mv": 0, "capacity": 4096,
            "fw_version": "sensor-0.3.0",
        },
    },
    {
        "name": "mid_life_device",
        "fields": {
            "protocol_version": 1, "record_size": RECORD_SIZE, "device_id": DEVICE_ID.hex(),
            "boot_id": 7, "next_seq": 20001, "collected_through": 19000, "secured_through": 18000,
            "uptime_s": 86400 * 3, "unix_time": EPOCH_2026_09_23, "dropped": 25, "battery_mv": 3650,
            "capacity": 65535, "fw_version": "sensor-0.3.0-rc1",
        },
    },
]
for d in DEVICE_INFO:
    d["hex"] = encode_device_info(d["fields"]).hex()

STATUS = [
    {"name": "open_ok", "fields": {"opcode": OPCODES["OPEN_SESSION"], "result": RESULTS["ok"], "seq": 42}},
    {"name": "read_no_session", "fields": {"opcode": OPCODES["READ_FROM"], "result": RESULTS["no_session"], "seq": 0}},
    {"name": "ack_out_of_range", "fields": {"opcode": OPCODES["ACK_SECURED"], "result": RESULTS["seq_out_of_range"], "seq": 41}},
    {"name": "unknown_opcode_bad_argument", "fields": {"opcode": 0x7f, "result": RESULTS["bad_argument"], "seq": 0}},
]
for s in STATUS:
    s["hex"] = encode_status(s["fields"]).hex()

COMMANDS = [
    {"name": "open_session", "command": {"name": "OPEN_SESSION", "session_id": SESSION_ID.hex()}},
    {"name": "set_time", "command": {"name": "SET_TIME", "unix_time": EPOCH_2026_09_23}},
    {"name": "read_from_all", "command": {"name": "READ_FROM", "seq": 1, "max_records": 0}},
    {"name": "read_from_window", "command": {"name": "READ_FROM", "seq": 4712, "max_records": 200}},
    {"name": "ack_collected", "command": {"name": "ACK_COLLECTED", "through_seq": 4711}},
    {"name": "ack_secured", "command": {"name": "ACK_SECURED", "through_seq": 4000}},
    {"name": "close_session", "command": {"name": "CLOSE_SESSION"}},
]
for c in COMMANDS:
    c["command"]["opcode"] = OPCODES[c["command"]["name"]]
    c["hex"] = encode_command(c["command"]).hex()

INVALID_COMMANDS = [
    {"name": "empty", "hex": "", "error": "bad_length"},
    {"name": "set_time_short", "hex": struct.pack("<BH", OPCODES["SET_TIME"], 1).hex(), "error": "bad_length"},
    {"name": "close_session_trailing_byte", "hex": struct.pack("<BB", OPCODES["CLOSE_SESSION"], 0).hex(), "error": "bad_length"},
    {"name": "unknown_opcode", "hex": struct.pack("<BI", 0x7f, 0).hex(), "error": "unknown_opcode"},
]

def _chunk_record(seq: int, value: float, uptime: int) -> str:
    """Records inside a chunk must have consecutive seqs, so they are built
    here rather than reused from VALID_RECORDS."""
    return encode_record({
        "version": RECORD_VERSION, "type": TYPE_SOIL_RESISTANCE_OHMS,
        "quality": QUALITY_OK, "flags": 0, "seq": seq, "time": uptime,
        "value": value, "boot_id": 1,
    }).hex()


CHUNKS = [
    {
        "name": "two_records_not_last",
        "first_seq": 1, "flags": 0,
        "records": [_chunk_record(1, 83520.0, 60), _chunk_record(2, 83400.0, 120)],
    },
    {
        "name": "one_record_last",
        "first_seq": 4711, "flags": CHUNK_FLAG_LAST,
        "records": [bytes.fromhex(VALID_RECORDS[1]["hex"]).hex()],
    },
    {
        "name": "empty_last",
        "first_seq": 20001, "flags": CHUNK_FLAG_LAST,
        "records": [],
    },
]
for ch in CHUNKS:
    recs = [bytes.fromhex(h) for h in ch["records"]]
    encoded = encode_chunk(ch["first_seq"], ch["flags"], recs)
    ch["hex"] = encoded.hex()
    ch["header"] = {
        "first_seq": ch["first_seq"], "count": len(recs), "flags": ch["flags"],
        "crc": crc16_ccitt_false(b"".join(recs)),
    }


def build_ble_json() -> str:
    doc = {
        "format": "ble",
        "protocol_version": PROTOCOL_VERSION,
        "service_uuid": SERVICE_UUID,
        "characteristics": {
            "device_info": CHAR_DEVICE_INFO,
            "control": CHAR_CONTROL,
            "data": CHAR_DATA,
            "status": CHAR_STATUS,
        },
        "sizes": {
            "advertising": ADVERTISING_SIZE,
            "device_info": DEVICE_INFO_SIZE,
            "status": STATUS_SIZE,
            "chunk_header": CHUNK_HEADER_SIZE,
            "max_records_per_chunk": MAX_RECORDS_PER_CHUNK,
        },
        "opcodes": OPCODES,
        "results": RESULTS,
        "advertising": ADVERTISING,
        "device_info": DEVICE_INFO,
        "status": STATUS,
        "commands": COMMANDS,
        "invalid_commands": INVALID_COMMANDS,
        "chunks": CHUNKS,
    }
    return json.dumps(doc, indent=2) + "\n"


def c_padded(b: bytes, size: int) -> str:
    assert len(b) <= size, (len(b), size)
    return c_bytes(b + bytes(size - len(b)))


def build_ble_header() -> str:
    max_cmd = max(len(bytes.fromhex(c["hex"])) for c in COMMANDS + INVALID_COMMANDS)
    max_chunk = max(len(bytes.fromhex(c["hex"])) for c in CHUNKS)
    L = [
        "// Generated by schema/tools/gen_vectors.py. Do not edit.",
        "#pragma once",
        "#include <stddef.h>",
        "#include <stdint.h>",
        "",
        f"#define BLE_VECTOR_PROTOCOL_VERSION {PROTOCOL_VERSION}",
        f'#define BLE_VECTOR_SERVICE_UUID "{SERVICE_UUID}"',
        f'#define BLE_VECTOR_CHAR_DEVICE_INFO "{CHAR_DEVICE_INFO}"',
        f'#define BLE_VECTOR_CHAR_CONTROL "{CHAR_CONTROL}"',
        f'#define BLE_VECTOR_CHAR_DATA "{CHAR_DATA}"',
        f'#define BLE_VECTOR_CHAR_STATUS "{CHAR_STATUS}"',
        f"#define BLE_VECTOR_ADVERTISING_SIZE {ADVERTISING_SIZE}",
        f"#define BLE_VECTOR_DEVICE_INFO_SIZE {DEVICE_INFO_SIZE}",
        f"#define BLE_VECTOR_STATUS_SIZE {STATUS_SIZE}",
        f"#define BLE_VECTOR_CHUNK_HEADER_SIZE {CHUNK_HEADER_SIZE}",
        f"#define BLE_VECTOR_MAX_RECORDS_PER_CHUNK {MAX_RECORDS_PER_CHUNK}",
        "",
        "struct AdvertisingVector {",
        "    const char* name;",
        f"    uint8_t bytes[{ADVERTISING_SIZE}];",
        "    uint8_t protocol_version; uint16_t pending; uint16_t battery_mv; uint8_t adv_flags;",
        "};",
        "static const AdvertisingVector kAdvertisingVectors[] = {",
    ]
    for a in ADVERTISING:
        f = a["fields"]
        L.append(f'    {{"{a["name"]}", {{{c_bytes(bytes.fromhex(a["hex"]))}}}, '
                 f'{f["protocol_version"]}, {f["pending"]}, {f["battery_mv"]}, {f["adv_flags"]}}},')
    L += [
        "};",
        f"static const size_t kAdvertisingVectorCount = {len(ADVERTISING)};",
        "",
        "struct DeviceInfoVector {",
        "    const char* name;",
        f"    uint8_t bytes[{DEVICE_INFO_SIZE}];",
        "    uint8_t protocol_version, record_size;",
        "    uint8_t device_id[6];",
        "    uint16_t boot_id;",
        "    uint32_t next_seq, collected_through, secured_through, uptime_s, unix_time, dropped;",
        "    uint16_t battery_mv, capacity;",
        "    const char* fw_version;",
        "};",
        "static const DeviceInfoVector kDeviceInfoVectors[] = {",
    ]
    for d in DEVICE_INFO:
        f = d["fields"]
        L.append(f'    {{"{d["name"]}", {{{c_bytes(bytes.fromhex(d["hex"]))}}}, '
                 f'{f["protocol_version"]}, {f["record_size"]}, {{{c_bytes(bytes.fromhex(f["device_id"]))}}}, '
                 f'{f["boot_id"]}, {f["next_seq"]}u, {f["collected_through"]}u, {f["secured_through"]}u, '
                 f'{f["uptime_s"]}u, {f["unix_time"]}u, {f["dropped"]}u, {f["battery_mv"]}, {f["capacity"]}, '
                 f'"{f["fw_version"]}"}},')
    L += [
        "};",
        f"static const size_t kDeviceInfoVectorCount = {len(DEVICE_INFO)};",
        "",
        "struct StatusVector {",
        "    const char* name;",
        f"    uint8_t bytes[{STATUS_SIZE}];",
        "    uint8_t opcode, result; uint32_t seq;",
        "};",
        "static const StatusVector kStatusVectors[] = {",
    ]
    for s in STATUS:
        f = s["fields"]
        L.append(f'    {{"{s["name"]}", {{{c_bytes(bytes.fromhex(s["hex"]))}}}, {f["opcode"]}, {f["result"]}, {f["seq"]}u}},')
    L += [
        "};",
        f"static const size_t kStatusVectorCount = {len(STATUS)};",
        "",
        "// Fields not used by an opcode are zero.",
        "struct CommandVector {",
        "    const char* name;",
        "    size_t len;",
        f"    uint8_t bytes[{max_cmd}];",
        "    uint8_t opcode;",
        "    uint8_t session_id[16];",
        "    uint32_t unix_time;",
        "    uint32_t seq;",
        "    uint16_t max_records;",
        "    uint32_t through_seq;",
        "};",
        "static const CommandVector kCommandVectors[] = {",
    ]
    for c in COMMANDS:
        cmd = c["command"]
        b = bytes.fromhex(c["hex"])
        sid = bytes.fromhex(cmd.get("session_id", "00" * 16))
        L.append(f'    {{"{c["name"]}", {len(b)}, {{{c_padded(b, max_cmd)}}}, {cmd["opcode"]}, '
                 f'{{{c_bytes(sid)}}}, {cmd.get("unix_time", 0)}u, {cmd.get("seq", 0)}u, '
                 f'{cmd.get("max_records", 0)}, {cmd.get("through_seq", 0)}u}},')
    L += [
        "};",
        f"static const size_t kCommandVectorCount = {len(COMMANDS)};",
        "",
        "struct InvalidCommandVector {",
        "    const char* name;",
        "    size_t len;",
        f"    uint8_t bytes[{max_cmd}];",
        "    const char* error;",
        "};",
        "static const InvalidCommandVector kInvalidCommandVectors[] = {",
    ]
    for c in INVALID_COMMANDS:
        b = bytes.fromhex(c["hex"])
        L.append(f'    {{"{c["name"]}", {len(b)}, {{{c_padded(b, max_cmd)}}}, "{c["error"]}"}},')
    L += [
        "};",
        f"static const size_t kInvalidCommandVectorCount = {len(INVALID_COMMANDS)};",
        "",
        "struct ChunkVector {",
        "    const char* name;",
        "    size_t len;",
        f"    uint8_t bytes[{max_chunk}];",
        "    uint32_t first_seq; uint8_t count, flags; uint16_t crc;",
        "};",
        "static const ChunkVector kChunkVectors[] = {",
    ]
    for ch in CHUNKS:
        b = bytes.fromhex(ch["hex"])
        h = ch["header"]
        L.append(f'    {{"{ch["name"]}", {len(b)}, {{{c_padded(b, max_chunk)}}}, '
                 f'{h["first_seq"]}u, {h["count"]}, {h["flags"]}, 0x{h["crc"]:04x}}},')
    L += [
        "};",
        f"static const size_t kChunkVectorCount = {len(CHUNKS)};",
        "",
    ]
    return "\n".join(L)


# ---------------------------------------------------------------------------


def main(argv: list[str]) -> int:
    assert f"{crc16_ccitt_false(b'123456789'):04x}" == "29b1", "CRC reference check failed"

    outputs = {
        VECTORS / "records.json": build_records_json(),
        VECTORS / "records_vectors.h": build_records_header(),
        VECTORS / "ble.json": build_ble_json(),
        VECTORS / "ble_vectors.h": build_ble_header(),
    }

    if "--check" in argv:
        stale = [p for p, content in outputs.items() if not p.exists() or p.read_text() != content]
        for p in stale:
            print(f"stale: {p.relative_to(HERE.parent.parent)}", file=sys.stderr)
        return 1 if stale else 0

    VECTORS.mkdir(parents=True, exist_ok=True)
    for p, content in outputs.items():
        p.write_text(content)
        print(f"wrote {p.relative_to(HERE.parent.parent)}")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
