#!/usr/bin/env python3
"""Generate golden vectors for the wire formats in schema/PROTOCOL.md.

Writes schema/vectors/records.json (for TypeScript and Go tests) and
schema/vectors/records_vectors.h (for the firmware's Unity tests). Both are
committed; CI re-runs this script and fails if the committed files differ.

Usage: python3 schema/tools/gen_vectors.py [--check]
"""
from __future__ import annotations

import json
import struct
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
VECTORS = HERE.parent / "vectors"

RECORD_VERSION = 1
RECORD_SIZE = 20
FLAG_EPOCH_VALID = 0x01

TYPE_SOIL_RESISTANCE_OHMS = 1
TYPE_BATTERY_MILLIVOLTS = 2

QUALITY_OK, QUALITY_LOW, QUALITY_HIGH, QUALITY_OPEN = 0, 1, 2, 3

EPOCH_2026_09_23 = 1790121600


def crc16_ccitt_false(data: bytes) -> int:
    crc = 0xFFFF
    for b in data:
        crc ^= b << 8
        for _ in range(8):
            if crc & 0x8000:
                crc = ((crc << 1) ^ 0x1021) & 0xFFFF
            else:
                crc = (crc << 1) & 0xFFFF
    return crc


def encode_record(r: dict) -> bytes:
    body = struct.pack(
        "<BBBBIIfH",
        r["version"], r["type"], r["quality"], r["flags"],
        r["seq"], r["time"], r["value"], r["boot_id"],
    )
    assert len(body) == RECORD_SIZE - 2
    return body + struct.pack("<H", crc16_ccitt_false(body))


def record(name: str, **fields) -> dict:
    r = {"version": RECORD_VERSION, **fields}
    return {"name": name, "hex": encode_record(r).hex(), "record": r}


VALID = [
    record(
        "soil_ok_epoch",
        type=TYPE_SOIL_RESISTANCE_OHMS, quality=QUALITY_OK, flags=FLAG_EPOCH_VALID,
        seq=1, time=EPOCH_2026_09_23, value=83520.0, boot_id=3,
    ),
    record(
        "soil_open_uptime",
        type=TYPE_SOIL_RESISTANCE_OHMS, quality=QUALITY_OPEN, flags=0,
        seq=4711, time=3600, value=-1.0, boot_id=1,
    ),
    record(
        "soil_low_first_seq",
        type=TYPE_SOIL_RESISTANCE_OHMS, quality=QUALITY_LOW, flags=0,
        seq=0, time=0, value=0.0, boot_id=0,
    ),
    record(
        "soil_high_large_value",
        type=TYPE_SOIL_RESISTANCE_OHMS, quality=QUALITY_HIGH, flags=FLAG_EPOCH_VALID,
        seq=1_000_000, time=EPOCH_2026_09_23 + 86_400, value=1_000_000.0, boot_id=12,
    ),
    record(
        "battery_max_counters",
        type=TYPE_BATTERY_MILLIVOLTS, quality=QUALITY_OK, flags=FLAG_EPOCH_VALID,
        seq=0xFFFFFFFF, time=0xFFFFFFFF, value=3712.0, boot_id=0xFFFF,
    ),
    record(
        "unknown_type_still_decodes",
        type=250, quality=QUALITY_OK, flags=0,
        seq=7, time=42, value=1.5, boot_id=2,
    ),
]


def invalid_vectors() -> list[dict]:
    base = bytes.fromhex(VALID[0]["hex"])

    bad_crc = bytearray(base)
    bad_crc[-1] ^= 0x01

    bad_version = bytearray(base)
    bad_version[0] = 2
    # CRC is recomputed so the version check, not the CRC check, must fire.
    bad_version[18:20] = struct.pack("<H", crc16_ccitt_false(bytes(bad_version[:18])))

    return [
        {"name": "short_input", "hex": base[:-1].hex(), "error": "short_input"},
        {"name": "unsupported_version", "hex": bytes(bad_version).hex(), "error": "unsupported_version"},
        {"name": "bad_crc", "hex": bytes(bad_crc).hex(), "error": "bad_crc"},
    ]


def build_json() -> str:
    doc = {
        "format": "record",
        "version": RECORD_VERSION,
        "size": RECORD_SIZE,
        "crc": {"name": "CRC-16/CCITT-FALSE", "check_input": "123456789", "check": "29b1"},
        "valid": VALID,
        "invalid": invalid_vectors(),
    }
    return json.dumps(doc, indent=2) + "\n"


def c_bytes(b: bytes) -> str:
    return ", ".join(f"0x{x:02x}" for x in b)


def c_float(v: float) -> str:
    s = repr(float(v))
    if "e" in s or "E" in s:
        s = f"{v:.1f}"
    return s + "f"


def build_header() -> str:
    lines = [
        "// Generated by schema/tools/gen_vectors.py. Do not edit.",
        "#pragma once",
        "#include <stddef.h>",
        "#include <stdint.h>",
        "",
        f"#define RECORD_VECTOR_VERSION {RECORD_VERSION}",
        f"#define RECORD_VECTOR_SIZE {RECORD_SIZE}",
        "",
        "struct RecordVector {",
        "    const char* name;",
        f"    uint8_t bytes[{RECORD_SIZE}];",
        "    uint8_t version, type, quality, flags;",
        "    uint32_t seq, time;",
        "    float value;",
        "    uint16_t boot_id;",
        "};",
        "",
        "static const RecordVector kRecordVectors[] = {",
    ]
    for v in VALID:
        r = v["record"]
        lines.append(
            f'    {{"{v["name"]}", {{{c_bytes(bytes.fromhex(v["hex"]))}}}, '
            f'{r["version"]}, {r["type"]}, {r["quality"]}, {r["flags"]}, '
            f'{r["seq"]}u, {r["time"]}u, {c_float(r["value"])}, {r["boot_id"]}}},'
        )
    lines += [
        "};",
        f"static const size_t kRecordVectorCount = {len(VALID)};",
        "",
        "struct InvalidRecordVector {",
        "    const char* name;",
        "    size_t len;",
        f"    uint8_t bytes[{RECORD_SIZE}];",
        "    const char* error;",
        "};",
        "",
        "static const InvalidRecordVector kInvalidRecordVectors[] = {",
    ]
    for v in invalid_vectors():
        b = bytes.fromhex(v["hex"])
        padded = b + bytes(RECORD_SIZE - len(b))
        lines.append(f'    {{"{v["name"]}", {len(b)}, {{{c_bytes(padded)}}}, "{v["error"]}"}},')
    lines += [
        "};",
        f"static const size_t kInvalidRecordVectorCount = {len(invalid_vectors())};",
        "",
    ]
    return "\n".join(lines)


def main(argv: list[str]) -> int:
    assert f"{crc16_ccitt_false(b'123456789'):04x}" == "29b1", "CRC reference check failed"

    outputs = {
        VECTORS / "records.json": build_json(),
        VECTORS / "records_vectors.h": build_header(),
    }

    if "--check" in argv:
        stale = [p for p, content in outputs.items() if not p.exists() or p.read_text() != content]
        for p in stale:
            print(f"stale: {p.relative_to(HERE.parent.parent)}", file=sys.stderr)
        return 1 if stale else 0

    VECTORS.mkdir(parents=True, exist_ok=True)
    for p, content in outputs.items():
        p.write_text(content)
        print(f"wrote {p.relative_to(HERE.parent.parent)}")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
